# Generated by Django 4.2.3 on 2023-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
