# Generated by Django 4.2.3 on 2023-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blight',
            name='type',
            field=models.CharField(blank=True, choices=[('DOT', 'CMV'), ('SLIM', 'TMV'), ('STRIPE', 'ToMV')], default='DOT', max_length=20, null=True),
        ),
    ]
