# Generated by Django 4.2.3 on 2023-09-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-created_at'], 'verbose_name': 'scrap', 'verbose_name_plural': 'Scraps'},
        ),
    ]
