# Generated by Django 4.2.3 on 2023-09-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_qna_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
    ]
