# Generated by Django 4.2.3 on 2023-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='explain',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
